### ISSUE TITLE
Use of tab for indentation at line 428 and 429 in game_state.py

### ISSUE THREAD

**Issue by ImYourCookie** [correlation-one/C1GamesStarterKit#120]
https://github.com/correlation-one/C1GamesStarterKit/blob/6001c4c69ce2371c15c37fafc53dbdadf8d53fae/python-algo/gamelib/game_state.py#L428

Everywhere else spaces are used, so this is a syntax error.

**Comment by Ryan-McPartlan** [comment]
Closed by #123
