### ISSUE TITLE
 Playground offline: DISCONNECTED. TIME EXCEEDED, INTERNET UNSTABLE, OR SERVER MAINTENANCE

### ISSUE THREAD

**Issue by Victerose** [correlation-one/C1GamesStarterKit#124]
We can only use `BY HAND` vs `BY HAND` in the playground. Playing with `BOSSES` or our algo will make the webpage crash as indicated by the following figure.

The same problem was mentioned on Jan 9th on [the forum](https://forum.c1games.com/t/playground-is-like-down/2036/2). 

![image](https://user-images.githubusercontent.com/14369936/160088901-dc0dab26-a24a-437f-9b7d-9525700b1208.png)

**Comment by Ryan-McPartlan** [comment]
This should be resolved
