### ISSUE TITLE
Refund of Firewalls

### ISSUE THREAD

**Issue by ZigZagNinja** [correlation-one/C1GamesStarterKit#38]
Sorry, but i cant seem to find anywhere how to remove already placed firewalls, mind telling me?
I mean in code of course

**Comment by 876584635678890** [comment]
https://github.com/correlation-one/C1GamesStarterKit/blob/master/algos/starter-algo-ZIPME/gamelib/game_state.py#L322

**Comment by skelly1324** [comment]
game_state.attempt_remove([x,y])
Where [x,y] is the location of the friendly firewall you want to remove.
You can find this sort of info in the documentation in starter_algo

In the future, please ask this sort of question in the forums.
